<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>


  <ItemGroup>
    <Content Update="wwwroot\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.35">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.35" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.35">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.35" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ProcessorApplication\ProcessorApplication.csproj">
      <!--<PrivateAssets>all</PrivateAssets>
      <ExcludeAssets>runtime</ExcludeAssets>-->
      <!--<Private>True</Private>-->
      <CopyLocalSatelliteAssemblies>True</CopyLocalSatelliteAssemblies>
      <Private>True</Private>
      <IncludeAssets>all</IncludeAssets>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\Scripts\" />
  </ItemGroup>  

</Project>
