// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProcessingModule.Database;

#nullable disable

namespace ProcessingModule.Migrations
{
    [DbContext(typeof(ProcessorDbContext))]
    [Migration("20260129063412_InitialProcessing")]
    partial class InitialProcessing
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.35");

            modelBuilder.Entity("ProcessorModule.Database.Models.OrchestratedTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CompletedTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("InitiatorUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhysicalPathRoot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("ProcessorModule.Database.Models.OrchestratedTaskSubJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CompletedTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParentJobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScriptId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StepDirectoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentJobId");

                    b.ToTable("ProcessingJobs");
                });

            modelBuilder.Entity("ProcessorModule.Database.Models.ScriptIndex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArtifactHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HashMatch")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManifestDirectoryPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessorVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScriptIdentifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScriptLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScriptVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Scripts");
                });

            modelBuilder.Entity("ProcessorModule.Database.Models.OrchestratedTaskSubJob", b =>
                {
                    b.HasOne("ProcessorModule.Database.Models.OrchestratedTask", "ParentJob")
                        .WithMany("SubJobs")
                        .HasForeignKey("ParentJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentJob");
                });

            modelBuilder.Entity("ProcessorModule.Database.Models.OrchestratedTask", b =>
                {
                    b.Navigation("SubJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
