using ProcessorApplication.ViewModels;

namespace ProcessorApplication.Models.User;

public class PagedUserListViewModel
{
    public int PageNumber { get; set; }
    public int PageSize { get; set; }
    public int TotalPages { get; set; }
    public int TotalCount { get; set; }
    public List<UserSummaryViewModel> Users { get; set; } = new List<UserSummaryViewModel>();
}


public class UserSummaryViewModel
{
    public string Id { get; set; }
    public string UserName { get; set; } // The autogenerated hash (Login ID)
    public string Name { get; set; }
    public string Surname { get; set; }
    public string DisplayNickname { get; set; }
    public bool IsLockedOut { get; set; }
}