<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Views\Providerless\Settings\_Settings_Reg_googledocs.cshtml" />
    <Content Remove="Views\Providerless\Settings\_Settings_Reg_rest.cshtml" />
    <Content Remove="Views\Providerless\Settings\_Settings_Tun_ngrok.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Views\Providerless\Settings\_Settings_Reg_googledocs.cshtml" />
    <None Include="Views\Providerless\Settings\_Settings_Reg_rest.cshtml" />
    <None Include="Views\Providerless\Settings\_Settings_Tun_ngrok.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ProcessorApplication\ProcessorApplication.csproj">
      <CopyLocalSatelliteAssemblies>True</CopyLocalSatelliteAssemblies>
      <Private>True</Private>
      <IncludeAssets>all</IncludeAssets>
    </ProjectReference>
  </ItemGroup>
  
</Project>
