using System.ComponentModel.DataAnnotations;

namespace ProviderlessModule.Configuration;

public class PortalAccessSettings
{
    public const string SectionName = "PortalSecuritySettings";

    public bool Enabled { get; set; }
    public bool RegistryEnabled { get; set; }

    /// <summary>
    /// Unique identifier for this clinic. 
    /// If null or empty, it will be autogenerated during module initialization, is persisted.
    /// Used in tunnel and registry parts
    /// </summary>
    [Display(Name = "Clinic Identifier")]
    public string ComputerId { get; set; }

    /// <summary>
    /// High-entropy secret key used for HMAC-SHA256 signatures and payload encryption.
    /// If null or empty, it will be autogenerated during module initialization, is persisted.
    /// Used in registry part for public url
    /// </summary>
    [Display(Name = "Shared Security Secret")]
    public string SharedSecret { get; set; }

    /// <summary>
    /// The local port your Kestrel/ASP.NET application is listening on.
    /// </summary>
    public int LocalPort { get; set; } = 5000;


    [Display(Name = "Selected Registry Mode")]

    public string ActiveRegistry { get; set; } = "github";
    //public RegistryProviderType ActiveRegistry { get; set; } = RegistryProviderType.GitHub;

    /// <summary>
    /// The preferred tunneling service to expose the local Kestrel server.
    /// </summary>
    [Required]
    [Display(Name = "Active Tunnel Provider")]

    public string SelectedTunnel { get; set; } = "cloudflare";
    //public TunnelProviderType SelectedTunnel { get; set; } = TunnelProviderType.Cloudflare;
}

public class TunnelProviderType
{
    public const string Static = "static";
    public const string Cloudflare = "cloudflare";
    public const string Ngrok = "ngrok";
}

public class RegistryProviderType
{
    public const string None = "none";
    public const string GitHub = "github";
    public const string GoogleDocs = "googledocs";
    public const string Rest = "rest";
}